server:
  port: 8000

admin:
  id: ${ADMIN_ID:}
  pw: ${ADMIN_PW:}

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    password: ${H2_PASSWORD:1234}
    username: sa

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
