server:
  port: 8010


admin:
  id: ${ADMIN_ID:}
  pw: ${ADMIN_PW:}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quiz_quiz?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: lje0818OVO!

  jpa:
    open-in-view: false
    show-sql: true
    database: mysql
